### PR TITLE
Full Plugin re-write

### PR DESCRIPTION
**Pull request by chetanyakan**
#### Summary

- Update to use new file dropdown plugin API for edit and file preview API for non-edit mode.
- Add new system console settings for `Disable SSL Verification` and `Encryption Secret`.
- Refactor APIs to use gorilla/mux
- Update File read/write APIs to allow Mattermost S3 file backends.
- Sync with [mattermost-plugin-starter-template](https://github.com/mattermost/mattermost-plugin-starter-template).
- Add CircleCI, CodeQL config files, and fix lint errors.
- Update Readme documentation.

#### Related PRs
- https://github.com/mattermost/mattermost-webapp/pull/8139

#### Screenshots

Peek 2021-05-25 18-37

- System console settings page

image

### CODE REVIEW

**Comment by chetanyakan** [comment]
@timar @kendy @mrkara I would love some feedback on this PR.

If you want to test the changes, here's a demo server with this plugin installed:

http://ec2-3-14-29-172.us-east-2.compute.amazonaws.com:8065/signup_user_complete/?id=aotbffnjhiy7xftdrs5icxm7ic


System admin user:

user: `sysadmin`
pass: `sysadmin`

**Comment by mrkara** [comment]
Hi @chetanyakan ! Thank you for the pull request. A lot of excellent work here, kudos!

But a bit hard to review all at once. Do you think it would be possible to have this as smaller PRs so that they can be reviewed, tested, and merged quickly?

**Comment by kendy** [comment]
@chetanyakan: Thanks so much - sorry this took so long.  Actually I think we should make you a committer, so that you can merge stuff yourself :-) - does that work for you?

**Comment by chetanyakan** [comment]
@kendy Thanks for looking at this PR.

There is actually a small issue in my last commit, which is fixed by this PR: https://github.com/CollaboraOnline/collabora-mattermost/pull/43

I am working on a couple more features, after which I would like to go through the full plugin code review process with Mattermost staff members, which is documented here:

- https://developers.mattermost.com/extend/plugins/community_process/#basic-code-review

Post that, I would like this plugin to be included in the Mattermost plugins marketplace, following the process mentioned here:

- https://developers.mattermost.com/extend/plugins/community-plugin-marketplace/


I would love to get commit access to this repo, which will make these next steps much easier.

**Comment by mrkara** [comment]
@chetanyakan You should have received an invitation to have write access to the repo. Thanks a lot for your contributions!

**Pull request merged**
