### PR TITLE
Feature: Create new file from templates and allow switching between view and edit modes

### PR DESCRIPTION
**Pull request by chetanyakan**
#### Summary

- Add file templates and create API to create a new file from template.
- Create a web-app modal to set file name and extension.
- Allow switching between edit/non-edit modes in full screen modal.
- Allow switching to edit mode in preview modal.
- Update the Readme file.
- Fixes https://github.com/CollaboraOnline/collabora-mattermost/issues/31

#### Screenshots

Peek 2021-06-22 12-09

Peek 2021-06-22 12-13

### CODE REVIEW

**Comment by mrkara** [comment]
Hi @chetanyakan ! Thanks again for a nice PR! :)

Is this ready to merge as far as you are concerned? If so, I'll just do a very quick scan of the commits, then merge it.

**Comment by chetanyakan** [comment]
@mrkara this PR is ready for review and should be good to merge.

**Comment by kendy** [comment]
@chetanyakan: Thank you so much for the feature, love it :-)

From the implementation point of view, I see that you first copy a template to a target location, and then as the second step, the user has to click it, correct?

To make things easier for the user, it might be better to use the "TemplateSource" property of the CheckFileInfo:

https://sdk.collaboraonline.com/docs/advanced_integration.html#templatesource

It allows you to create and open the new file created from the template provided via the TemplateSource right away.

I'd suggest to move to this mechanism - but completely up to you if you still want to do it as part of this PR, or if you prefer to merge this one as is, and update the implementation in a follow-up PR?  What's your preference?

**Review by kendy — APPROVED** [review]
Approving - up to you if you migrate to TemplateSource now or later.

**Comment by chetanyakan** [comment]
> to use the "TemplateSource" property of the CheckFileInfo

@kendy This is great information. I didn't know about this.

But, I still have some doubts regarding the implementation this way.
Right now, when the user tries to create the file from the plugin upload component, we upload the file to Mattermost and create a post with the same file as an attachment.
The way you are suggesting, we will directly allow users to edit a new file from the template. But, then we have to handle the file upload and post creation on save.

Might be a little tricky and require some work. So, I've created a new issue to tackle this later: https://github.com/CollaboraOnline/collabora-mattermost/issues/47

**Pull request merged**
