### PR TITLE
Fix for Viewing / Editing of all doc type except PDF not possible any…

### PR DESCRIPTION
**Pull request by lordbaco**
Related to https://github.com/CollaboraOnline/collabora-mattermost/issues/17

### CODE REVIEW

**Comment by kendy** [comment]
@lordbaco: Thanks so much for your fixes!  I've merged your changes on top of the @mikekaganski 's changes, hope that was right :-)

Do you plan to do any more changes to the plugin, please?

**Comment by lordbaco** [comment]
Thanks for the merge. 

The main fix was done by @mikekaganski, I just fixed a small typo with the len() in the j loop
As I used an older version of npm, I also fixed reported issues linked to javascript.

The plugin is working perfectly. I would do two things
- Create an official compiled version for 1.0.1 similar to https://github.com/lordbaco/collabora-mattermost/releases/tag/1.0.1
- Add a button to create new document from scratch directly in Mattermost similar to what you can do in Nextcloud

**Comment by mrkara** [comment]
Hi @lordbaco, and thank you for your nice work on this! :)

I wonder if you would be interested in taking on (some of) these tasks. Maybe the second one (adding the button)?

**Comment by lordbaco** [comment]
No yet. I plan to close my github account.
Thanks for the merge and the 1.1.0 release.

**Pull request merged**
